#!/usr/bin/python3

import sys
import time
from threading import Thread

from flask import Flask, render_template
import pygal

from controller import Controller

app = Flask(__name__)
data = []

# TODO
# * automatically update chart
# * controller records temps in db
# * config for temperature sensor dir and relay gpio
# * prettify web output
# * also log enable/disable state of controller

@app.route('/')
def index():
    chart = pygal.XY()
    chart.title = 'Measured Temperature'
    chart.show_legend = False
    chart.x_title='Seconds Since Start'
    chart.y_title='Temperature in Fahrenheit'
    chart.style = pygal.style.CleanStyle()
    chart.add('Temperature', data)

    return render_template('index.html',target=app.config['TARGET_TEMP'],chart=chart.render().decode("utf-8"))

class ControllerThread(Thread):
    def __init__(self, data, target):
        Thread.__init__(self)
        self.data = data
        self.target = target

    def run(self):
        controller = Controller(values=data)
        controller.run(self.target)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("usage:", sys.argv[0], "<target temp (degrees fahrenheit)>")
        sys.exit(0)

    target_temp = int(sys.argv[1])
    t = ControllerThread(data,target_temp)
    t.start()
    app.config['TARGET_TEMP'] = target_temp
    app.run(host='0.0.0.0', port=80, debug=True)

