#!/usr/bin/python3

import sys
import signal
import time
from threading import Thread

from flask import Flask, render_template, jsonify
import pygal

from controller import Controller

app = Flask(__name__)
data = []
stop_controlling = False

@app.route('/')
def index():
    return render_template('index.html',target=app.config['TARGET_TEMP'])

@app.route('/_get_chart')
def get_chart():
    chart = pygal.XY()
    chart.title = 'Measured Temperature'
    chart.show_legend = False
    chart.x_title='Seconds Since Start'
    chart.y_title='Temperature in Fahrenheit'
    chart.style = pygal.style.CleanStyle()
    chart.add('Temperature', data)

    return chart.render()

class ControllerThread(Thread):
    def __init__(self, data, target):
        Thread.__init__(self)
        self.data = data
        self.target = target
        self.controller = Controller(values=self.data)

    def run(self):
        self.controller.run(self.target)

    def stop(self):
        controller.stop()

def exit_handler(signal, frame):
    controller_thread.stop()
    sys.exit(0)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("usage:", sys.argv[0], "<target temp (degrees fahrenheit)>")
        sys.exit(0)

    target_temp = int(sys.argv[1])
    controller_thread = ControllerThread(data,target_temp)
    signal.signal(signal.SIGINT, exit_handler)
    controller_thread.start()
    app.config['TARGET_TEMP'] = target_temp
    app.run(host='0.0.0.0', port=6080)

